<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Vital extends Model
{
    use HasFactory;
    protected $fillable = [
        'patient_code',
        'cc',
        'pohx',
        'lee',
        'pmhx',
        'pfohx',
        'odunaided',
        'odpinhole',
        'odaxis',
        'osunaided',
        'ospinhole',
        'osaxis',
        'lodsph',
        'lodcyl',
        'lodaxis',
        'lodva',
        'lossph',
        'loscyl',
        'losaxis',
        'losva',
        'addsph',
        'addcyl',
        'addaxis',
        'addva',
        'arodsphere',
        'arodcyl',
        'arodaxis',
        'arossphere',
        'aroscyl',
        'arosaxis',
        'rodsph',
        'rodcyl',
        'rodaxis',
        'rossph',
        'roscyl',
        'rosaxis',
        'srodsphere',
        'srodcyl',
        'srodaxis',
        'srodva',
        'srodadd',
        'srodnva',
        'srossphere',
        'sroscyl',
        'srosaxis',
        'srosva',
        'srosadd',
        'srosnva',
        'fodsph',
        'fodcyl',
        'fodaxis',
        'fodva',
        'fodadd',
        'fodnva',
        'fossph',
        'foscyl',
        'fosaxis',
        'fosva',
        'fosadd',
        'fosnva',
        'eyelidod',
        'eyelidos',
        'conjuctivaod',
        'conjuctivaos',
        'corneaod',
        'corneaos',
        'pupilod',
        'pupilos',
        'irisod',
        'irisos',
        'lensod',
        'lensos',
        'vitreousod',
        'vitreousos',
        'cdratiood',
        'cdratioos',
        'macularod',
        'maculaos',
        'odccct',
        'odnct',
        'oscct',
        'osnct',
    ];
}
